### ISSUE TITLE
Problem with hbeat

### ISSUE THREAD

**Issue by charettemtb** [olebrun/xPL.Arduino#1]
First of all, thank you for this great job.

The heartbeat interval does not respect the xPL standard.
He is actualy in second and the standard said anything from five minutes to thirty minutes.

Can you take this issue in care.

Thank you

**Comment by olebrun** [comment]
Hi, thank you for your interest :)
You're right, I will fix it soon.

Thanks

**Comment by olebrun** [comment]
I have change the default heartbeat interval from 15s to 5min.
_I should review my definition of "soon" :/_
